@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyMjkwNzV9.WC8BcZgOMuLIItAANCmZCZsRHaGEbxAoUvwU3Gx6ihI
################
### PRODUCTS ###
################

### Index
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

### Show Product
GET http://localhost:3000/products/2.json

### Create Product
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Cups",
  "price": "20",
  "description": "Solo 16 oz Plastic Party Cups, Red, 1,000 Cups/Carton - These Plastic Party Cups are ideal for any occasion. They deliver superior value and suitable for any cold application. Cups are made of sturdy, rigid polystyrene."
}


### Update Product
PATCH http://localhost:3000/products/10
Content-Type: application/json

{
  "supplier_id": 1
 }

### Delete Products
DELETE http://localhost:3000/products/3

### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "David Lin",
  "email": "DL@example.com",
  "password": "testing",
  "password_confirmation": "testing"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "AL@example.com",
  "password": "testing"
}

### Order create

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 2,
  "quantity": 3
}

### Users update

PATCH http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "admin": true
}

### Product_image create
### For some reason this does not work. Investigate
### Error: uninitialized constant ProductImagesController::Product_image

POST http://localhost:3000/product_images.json
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "product_id": 1,
  "rank": 1,
  "url": "https://www.irishtimes.com/polopoly_fs/1.4473007.1612185073!/image/image.jpg"
}


### Category create
### For some reason this does not work. Investigate
### Error: uninitialized constant ProductImagesController::Product_image

POST http://localhost:3000/categories
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "name": "Accessories"
}
