POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Cups",
  "price": "20",
  "image_url": "https://de2wfhoo6xqi5.cloudfront.net/size/600/a35/380/2773a9aa81f99102210657d5a347902c4a.jpg",
  "description": "Solo 16 oz Plastic Party Cups, Red, 1,000 Cups/Carton - These Plastic Party Cups are ideal for any occasion. They deliver superior value and suitable for any cold application. Cups are made of sturdy, rigid polystyrene."
}
###
GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/2.json

###
PATCH http://localhost:3000/products/10
Content-Type: application/json

{
  "supplier_id": 1
 }

###
DELETE http://localhost:3000/products/3